package com.tcontur.central.inspectoria.iniciar.qr

import com.tcontur.central.core.utils.currentTimeMillis
import kotlinx.datetime.LocalDateTime
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toInstant
import kotlinx.serialization.json.*

/**
 * Parses QR codes generated by the Tcontur conductor app.
 *
 * Supported formats (JSON arrays):
 *
 *  v0 – 5 elements (legacy, no timestamp):
 *    [unidad, subida, [lat, lng], salida, [[boletoId, fin], …]]
 *
 *  v1 – 7 elements (first element = 1, includes timestamp):
 *    [1, unidad, subida, [lat, lng], salida, [[boletoId, inicio, fin], …], "yyyy-MM-dd'T'HH:mm:ss"]
 *    The timestamp must be within 5 minutes of now (America/Lima timezone).
 */
object QrParser {

    private val json = Json { ignoreUnknownKeys = true }

    /** @throws QrError on any validation failure */
    fun parse(rawValue: String): QrData {
        if (rawValue.isBlank()) throw QrError.Empty

        val array = try {
            json.parseToJsonElement(rawValue.trim()).jsonArray
        } catch (_: Exception) {
            throw QrError.InvalidFormat
        }

        if (array.isEmpty()) throw QrError.InvalidFormat

        return when {
            array.size == 5                              -> parseV0(array)
            array[0].jsonPrimitive.intOrNull == 1        -> parseV1(array)
            else                                         -> throw QrError.UnsupportedVersion
        }
    }

    // ── v0 ────────────────────────────────────────────────────────────────────

    private fun parseV0(a: JsonArray): QrData {
        val unidad = a[0].jsonPrimitive.int
        val subida = a[1].jsonPrimitive.int
        val pos    = a[2].jsonArray
        val lat    = pos[0].jsonPrimitive.double
        val lng    = pos[1].jsonPrimitive.double
        val salida = a[3].jsonPrimitive.int
        val cortes = a[4].jsonArray.map { c ->
            val ca = c.jsonArray
            QrCorte(boletoId = ca[0].jsonPrimitive.int, inicio = 0, fin = ca[1].jsonPrimitive.int)
        }
        return QrData(version = 0, unidad, subida, lat, lng, salida, cortes)
    }

    // ── v1 ────────────────────────────────────────────────────────────────────

    private fun parseV1(a: JsonArray): QrData {
        val unidad    = a[1].jsonPrimitive.int
        val subida    = a[2].jsonPrimitive.int
        val pos       = a[3].jsonArray
        val lat       = pos[0].jsonPrimitive.double
        val lng       = pos[1].jsonPrimitive.double
        val salida    = a[4].jsonPrimitive.int
        val cortes    = a[5].jsonArray.map { c ->
            val ca = c.jsonArray
            QrCorte(
                boletoId = ca[0].jsonPrimitive.int,
                inicio   = ca[1].jsonPrimitive.int,
                fin      = ca[2].jsonPrimitive.int
            )
        }
        val timestamp = a[6].jsonPrimitive.content

        // ── Timestamp validation (5-minute window, America/Lima) ──────────────
        val qrMillis  = parseTimestamp(timestamp) ?: throw QrError.InvalidFormat
        val nowMillis = currentTimeMillis()
        val diff      = nowMillis - qrMillis

        if (diff < -5_000L)   throw QrError.FutureDate  // QR is from the future
        if (diff > 300_000L)  throw QrError.Expired     // older than 5 minutes

        return QrData(version = 1, unidad, subida, lat, lng, salida, cortes)
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Parses "yyyy-MM-dd'T'HH:mm:ss" as America/Lima and returns epoch millis.
     * Returns null if parsing fails.
     */
    private fun parseTimestamp(ts: String): Long? = try {
        val ldt  = LocalDateTime.parse(ts)
        val zone = TimeZone.of("America/Lima")
        ldt.toInstant(zone).toEpochMilliseconds()
    } catch (_: Exception) {
        null
    }
}
